name: CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify the desired distribution of Java

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: build/test-results

      - name: Generate Allure report
        run: ./gradlew allureReport

      - name: Publish Allure report
        uses: actions/upload-artifact@v2
        with:
          name: Allure Report
          path: build/reports/allure-report